[package]
name = "shader-crusher"
version = "0.7.2-alpha"
authors = ["Andreas Neukoetter <andreas@omni-mad.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# src/glsl/ is a vendored copy of the BSD-3-Clause `glsl` crate (see LICENSE-glsl).
license = "MIT AND BSD-3-Clause"
description = "A little helper to optimize glsl shaders for size."
readme = "README.md"
homepage = "https://github.com/AndreasOM/shader-crusher"
repository = "https://github.com/AndreasOM/shader-crusher"
keywords = ["tools", "gamedev"]
categories = ["command-line-utilities","compression","graphics"]
exclude = ["bench/"]

[[bin]]
name="shader-crusher"
path="src/main.rs"

[lib]
# crate-type = ["rlib", "staticlib"]
# crate-type = ["cdylib"]
# crate-type = ["rlib", "staticlib", "dylib"]

[dependencies]
clap = { version= "4.5" }
entropy = { version="0.4.1" }
libc = { version="0.2.132" }
nom = { version="7", default-features=false, features=["std"] }
regex = { version="1.6.0" }

